services:
  ModularMonolithDb:
    image: postgres
    container_name: ModularMonolithDb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ModularMonolithDb
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    
  vm.modular.api:
    image: vm.modular.api
    build:
      context: .
      dockerfile: src/Bootstrapper/vm.modular.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=db;Port=5432;Database=ModularMonolithDb;User Id=admin;Password=admin1234;"
    
    depends_on:
      - ModularMonolithDb
    ports:
      - "8080:8080"

volumes:
  postgres_data:
