<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Discount.Domain\Discount.Domain.csproj"/>
        <ProjectReference Include="..\Discount.Infrastructure\Discount.Infrastructure.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Features\Commands\"/>
        <Folder Include="Features\Queries\"/>
    </ItemGroup>
</Project>
